### PR TITLE
Page structure

### PR DESCRIPTION
**Pull request by belindac-vd**

### CODE REVIEW

**Comment by belindac-vd** [comment]
Just setting up repo permissions, needed a MR

**Comment by jennikate** [comment]
Ready to be reviewed

- nav extracted from header, works bar one bug (noted below)
- content array created so we can easily change headers and blurbs
- page container created which pulls together the elements needed for pages and passes down the page urlStub
- page intro created which provides the intro panels for the page, and includes the functioning back link
- sectionTable which can be used when there is table data to display
- sectionTabs which can be used when there is tab data to display
- sectionSignInWelcome which should appear at the top of the page when a user first logs in (need to confirm this is correct behaviour with Tom & then build that part)

Known bugs to fix

- need to add linter and fix missing ';'
- on navigation when a user clicks a link, the link remains in 'active' state until the user clicks elsewhere. It should only be active while the key/mouse down is in effect

**Comment by jennikate** [comment]
Additions:

- added linter and fixed errors
- Hardcode the url on submit advanced report page 
- Use navLinks instead of navData as that describes them better
- Separate contentArray in import lists as it’s a different type of file

**Comment by jennikate** [comment]
Split up and commited as multiple PRs with a few minor changes

**Pull request closed without merging**
